### ISSUE TITLE
What's your (mathsimd::float2) sign?

### ISSUE THREAD

**Issue by dreness** [muramasa2402/Gravity#1]
Hi :) Sorry for the intrusion, however I'm interested in trying your Gravity project, but I'm unable to get it to build for lack of a 'sign' member on mathsimd::float2. Since mathsimd is one of your own libraries, I assume by default that you're not using it incorrectly, so perhaps there is some other environmental difference that yields the following failure on my system (macOS / 10.14.5)

```
[build] [ 30%] Building CXX object CMakeFiles/Gravity.dir/src/BH_Tests.cpp.o
[build] [ 30%] Building CXX object CMakeFiles/Gravity.dir/src/CollisionGrid.cpp.o
[build] In file included from /Users/andre/work/Gravity/src/MovementSystem.cpp:4:
[build] /Users/andre/work/Gravity/src/../include/Utils.hpp:21:67: error: no member named 'sign' in 'mathsimd::float2'
[build]     p = mathsimd::float2::minimum(p, world.max * (1.f - world.max.sign()*0.0001f));
[build]                                                         ~~~~~~~~~ ^
```

Indeed, that appears to be true. I double checked that world.max actually is a mathsimd::float2. That type is defined [here](https://github.com/muramasa2402/Mathsimd/blob/master/include/float2.hpp) and I definitely don't see any "sign" members.

I got this all loaded up in VS Code and all the "intellisense" signals in the IDE agreed with what the compilers are saying about 'sign' being an unknown thing (I tried both apple's latest clang++ and also g++-9 from homebrew).

I'm kind of all-thumbs when it comes to c++, so haven't yet attempted simply writing my own 'sign' implementation - which I'm guessing is supposed to just return a same-sized structure, but with values replaced with 1 or -1 (or 0 or NaN?) depending on the sign of the input value. I looked at various other 'sign' implementations which all strongly suggested that whatever I might do as a novice would probably be significantly slower than all this bitshifting and whathaveyou that is over (under?) my head. Anyway, thanks for your time :)

**Comment by bryanwjy** [comment]
Hi, apologies for the mistake. I forgot to push the latest changes from my mathsimd library. It should be fixed now. And yes, you're right about the sign function returning 1 and -1; I don't think it would have mattered much if you implemented it on your own with non-SSE code, it's unlikely to affect the simulation that much. The program is mainly bottlenecked by the collision detection and the force interactions between the particles, which I don't think uses that function much or at all.

Also on a side note, if you're not on a powerful processor (I was on an i5 quad-core 2017 MBP), I would suggest changing the number of particles to a smaller number (line 17 in src/World.cpp). The `n` value on that line is the square root of the number of particles (I used the square root as I was trying something before and I haven't been bothered to change it 😅).

Also, I haven't had the time to benchmark/test the code thoroughly. Let me know if there are any other issues.

**Comment by dreness** [comment]
Yep, all better now. Thanks!
